language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

services:
  - mongodb

install:
  - cd client && npm install && cd ..
  - npm install

script:
  - npm run test
  - cd client && npm run test && cd ..

